spring.application.name=LogicCircuit
spring.main.allow-bean-definition-overriding=true

# Spring Datasource
spring.datasource.url=jdbc:mysql://192.168.0.2:3306/logic_circuit?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.type-aliases-package=com.example.LogicCircuit.entity
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Server
server.port=8081
